services:

  mongodb:
    image: mongo:8
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - ./seed/mongo:/docker-entrypoint-initdb.d
    networks:
      - payment-network

  otp-mysql:
    image: mysql:8
    container_name: otp-mysql
    ports:
     - "3307:3306"
    environment:
      MYSQL_DATABASE: otp_service_db
      MYSQL_ROOT_PASSWORD: ${OTP_DB_PASSWORD}
    volumes:
      - otp-mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${OTP_DB_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - payment-network

  redis:
      image: redis:8
      container_name: payment-redis
      ports:
        - "6379:6379"
      networks:
        - payment-network

  auth-service:
    build:
      context: ./Backend/auth-service
    container_name: auth-service
    ports:
      - "3000:3000"
    env_file:
      - ./Backend/auth-service/.env
    depends_on:
      - mongodb
    networks:
      - payment-network

  balance-management:
    build:
      context: ./Backend/balance-management
    container_name: balance-management
    ports:
      - "3001:3001"
    environment:
      SQLSERVER_USERNAME: ${SQLSERVER_USERNAME}
      SQLSERVER_PASSWORD: ${SQLSERVER_PASSWORD}
    networks:
      - payment-network
  
  otp-service:
    build: ./Backend/otp-service
    container_name: otp-service
    ports:
      - "8083:8083"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://otp-mysql:3306/otp_service_db
      SPRING_DATASOURCE_USERNAME: ${OTP_DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${OTP_DB_PASSWORD}

      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}

      INTERNAL_SERVICE_TOKEN: ${INTERNAL_SERVICE_TOKEN}
    depends_on:
      otp-mysql:
        condition: service_healthy
    networks:
      - payment-network

  tuition:
    build:
      context: ./Backend/tuition-management
    container_name: tuition-management
    ports:
      - "3002:3002"
    environment:
      SQLSERVER_USERNAME: ${SQLSERVER_USERNAME}
      SQLSERVER_PASSWORD: ${SQLSERVER_PASSWORD}
    networks:
      - payment-network

  payment:
    build:
      context: ./Backend/payment-service
    container_name: payment-service
    ports:
      - "8080:8080"
    environment:
      SQLSERVER_USERNAME: ${SQLSERVER_USERNAME}
      SQLSERVER_PASSWORD: ${SQLSERVER_PASSWORD}
    depends_on:
      - redis
    networks:
      - payment-network

volumes:
    mongo-data:
    otp-mysql-data:
networks:
  payment-network:
    driver: bridge