CREATE TABLE IF NOT EXISTS otps (
    id BIGINT NOT NULL AUTO_INCREMENT,
    payment_id VARCHAR(100) NOT NULL UNIQUE,
    code VARCHAR(6) NOT NULL,
    email VARCHAR(150) NOT NULL,
    expires_at DATETIME NOT NULL,
    used BOOLEAN NOT NULL DEFAULT FALSE,
    attempts INT NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (id)
);