spring.application.name=payment-service
spring.datasource.url=jdbc:sqlserver://host.docker.internal:1433;databaseName=PaymentDB;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=123456
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.security.oauth2.resourceserver.jwt.public-key-location=classpath:keys/public.pem

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true